spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/water_quality_develop
    username: postgres
    password: postgres1
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect