spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/water_quality_develop
    username: postgres
    password: postgres1
  jpa:
    hibernate:
      ddl-auto: update #create, validate, create-drop, update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true