spring:
  profiles:
    active: dev

server:
  port: 8080

REMOTE_BASE_URI : http://localhost:8080/

management:
  endpoints:
    web:
      exposure:
        include: "*"

application:
  jwt:
    secret: "======================Power=Of=Spring==========================="
    expirationInMs: 86400000 #24 hours - in general short is better